### ISSUE TITLE
Add a solution for customized-built-ins that rely on children for setup

### ISSUE THREAD

**Issue by franktopel** [WebReflection/html-parsed-element#1]
While this neatly solves 99% of practical problems with autonomous custom elements, it still doesn't fully cover the issue since there is also the unloved customized-built-ins like `<table is="data-table">` , `<select is="custom-select">` etc.

The approach could be to have a function which you pass a reference to the component's `this` and which adds the required functionality.

**Comment by WebReflection** [comment]
You can `HTMLParsedElement.withParsedCallback(AnyClass);` now, with the ability to use `AnyClass, 'upgraded'` if you prefer `upgradedCallback` instead of `parsedCallback`.
