### ISSUE TITLE
Clarification on need when compared to requestAnimationFrame

### ISSUE THREAD

**Issue by ProjectBarks** [WebReflection/html-parsed-element#11]
I have been reading through several of the threads, including #2. Could it be broken down why we would need this over a simple `requestAnimationFrame`?

Right now it seems most cases would be better off with a `requestAnimationFrame`, what are the key pieces of this implementation which necessitate all the extra code? 

Asking out of curiosity so I can help migrate to a more consistent solution in my teams codebase. Right now there are several places where my teammates bypass the issue with a `requestAnimationFrame`

**Comment by WebReflection** [comment]
`requestAnimationFrame` doesn't grant anything at all ... a flushed partial page could take longer than 16ms but it's also true that only browsers can provide a native robust way to solve this haunting issue of the Web, yet they don't want to do that for reasons beyond my comprehension.

If you are confident *rAF* is all you need, then use *rAF*, I have no stake in this, I just provide solutions that have been proven to work for a while.
