### ISSUE TITLE
TypeError and questions about renaming of parsedCallback

### ISSUE THREAD

**Issue by fkleinro** [WebReflection/html-parsed-element#3]
I've tried to include 'html-parsed-element' into my project. The following questions and problems arise for me:

1.) The code causes an error in my project  (_Uncaught TypeError: Property description must be an object: false in Chrome) . In addition, it is not clear to me what this is good for.

```
   get [name]() {
            const value = init.has(this) ?
              (init.get(this) === true) :
              isParsed(this);
            if (value)
              Object.defineProperty(this, name, {value});
            return value;  // return { value }
          }
```

2.) After removal or correction of this via 'return { value }. Is this right? I probably get a subsequent misunderstanding that if a connectedCallback method exists in a custom element, the parsedCallback method is no longer called - Is this so intended ? With a built-in-custom element this works.

Code in html-parsed-element
```
             if (connectedCallback)
                connectedCallback.apply(this, arguments);         
              if (method in this && !init.has(this)) {
```

Example:
```
customElements.define('my-element', class extends HTMLParsedElement {

	connectedCallback() {
		console.log('connectedCallback called');		
	}
			
	parsedCallback() {
		console.log('parsedCallback never called if connectedCallback exists');		
	}
})

```
3.) The name of the method parsedCallback cannot be changed, because from my point of view in the following code this is still corded hard.

```
 const parsedCallback = el => {
    init.set(el, true);
    el.parsedCallback();
  };
```

**Comment by WebReflection** [comment]
thanks for the report.

  1. fixed (regression of 0.2)
  2. "_if a connectedCallback method exists in a custom element, the parsedCallback method is no longer called_". It will be called every time the element is connected. Only parsedCallback is called only once.
  3. fixed
