### ISSUE TITLE
Missing IE11 support

### ISSUE THREAD

**Issue by fkleinro** [WebReflection/html-parsed-element#4]
With Babel we also support IE11 in my project. Since the code of html-parsed-element is in ES6 , so it comes to the following error message:

Class constructor HTMLParsedElement cannot be invoked without 'new'

```
class MyCustomElement extends HTMLParsedElement {
    
   
    constructor(...args) {
        const self = super(...args);   // Error  
        return self;
    }
```

If I use Babel on ES6, then everything works.

Babel Example:
```
{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "chrome": "70"   
        ...

````

**Comment by WebReflection** [comment]
> Since the code of html-parsed-element is in ES6

... that means you should `import` / `require` it and let your transpiler do the rest ... like every other library as module.

**Comment by WebReflection** [comment]
P.S. just in case it's needed ...

```js
// esm with a good bundler
import HTMLParsedElement from 'html-parsed-element';

// esm with a less good bundler
import HTMLParsedElement from 'html-parsed-element/esm';

// esm via CDN (or you can use a relative/absolute path)
import HTMLParsedElement from 'https://unpkg.com/html-parsed-element/esm/index.js';


// cjs
const HTMLParsedElement = require('html-parsed-element');

// bad cjs bundler
const HTMLParsedElement = require('html-parsed-element/cjs');
```

that's it.

**Comment by franktopel** [comment]
The reason for the problem will be that it's very common for `babel-loader` within a webpack stack to exclude `node_modules` (which are expected to be ES5 and not need transpiling). 
 
Typical config:

```javascript
module: {
  rules: [
    {
      test: /\.js$/,
      exclude: /node_modules/,
      use: {
        loader: 'babel-loader',
        options: {
          presets: ['@babel/preset-env']
        }
      }
    }
  ]
}
```

For that very common setup case, I'd vote for re-opening of this issue (I'd re-title the issue accordingly).

Excluding `node_modules` is even recommended on `babel-loader` side:

> ## babel-loader is slow!
> Make sure you are transforming as few files as possible. Because you are probably matching /\.js$/, you might be transforming the node_modules folder or other unwanted source.

> To exclude node_modules, see the exclude option in the loaders config as documented above.

>https://github.com/babel/babel-loader

If you so desire, I can also create a separate issue for this.

**Comment by WebReflection** [comment]
Classes are not for transpilers, or better, every transpiler has its own way to transform classes.

TypeScript just breaks everything, Babel 6 needs a plugin, Babel 7 works with some polyfill and not some other ... I am not planning to care at all about all these issues that have nothing to do with this specific code.

Whenever there are native classes / built-ins involved, I let you solve the issue as you can, instead of drowning under tickets that don't belong here.

**Be sure your bundler reaches this module too** is the only advice for built in classes of any kind I can give.

**Comment by franktopel** [comment]
Okay, I understand and agree. Nonetheless that should be reflected in the README, which is part of the reason I have submitted a PR https://github.com/WebReflection/html-parsed-element/pull/5
