### ISSUE TITLE
Mutationobserver triggers too early (childlist incomplete)

### ISSUE THREAD

**Issue by franktopel** [WebReflection/html-parsed-element#9]
We have a `tabs-component` component which has ***alot*** of children/descendant nodes.

This is the basic structure:

```html
<tabs-component active-tab="1">
    <ul class="tab-links">
        <li><button type="button">A</button></li>
        <li><button type="button">B</button></li>
        <li><button type="button">C</button></li>
        <li><button type="button">D</button></li>
        <!-- potentially many more lis items and buttons, up to 30 -->
    </ul>
    <div id="A"><!-- ALOT of HTML, like hundreds of lines --></div>
    <div id="B"><!-- ALOT of HTML, like hundreds of lines --></div>
    <div id="C"><!-- ALOT of HTML, like hundreds of lines --></div>
    <div id="D"><!-- ALOT of HTML, like hundreds of lines --></div>
    <!-- potentially many more divs, up to 30 -->
</tabs-component>
``` 
Each of those `div` which serve as tab content containers can host another (or even several) `<tabs-component>`  and many have `<data-table>` children.

Now when the `tabs-component` wants to do its setup, the mutationobserver triggers with the following HTML available (as seen in Chrome's debugger):

```html
<tabs-component active-tab="1">
    <ul class="tab-links">
        <li><button type="button">A</button></li>
        <li><button type="button">B</button></li>
        <li><button type="button">C</button></li>
        <li><button type="button">D</button></li>
    </ul>
    <div id="A"><!-- ALOT of HTML, like hundreds of lines --></div>
</tabs-component>
```

Is there a way to only trigger the mutationobserver when all children have been added to the tree?

**Comment by irhadkul** [comment]
To make matters worse, the changes which we are getting in the `MutationObserver` are simply random, e.g. sometimes the mutation observer triggers with only one of those `div` being in the changelist, sometimes 2, sometimes 3, but in all the cases the childlist was nowhere near complete.

**Comment by WebReflection** [comment]
> Is there a way to only trigger the mutationobserver when all children have been added to the tree?

no, as there's no mechanism to know when the end of a node has been reached, while parsing.

I wish @rniwa would read all these bugs you are filing here since none of these are strictly related to my code, just limits of the DOM API nobody in implementation seems to see.

**Comment by WebReflection** [comment]
P.S. I've closed this as there's literally nothing I can do. If anyone finds anything, PRs welcome.

**Comment by franktopel** [comment]
*as there's no mechanism to know when the end of a node has been reached* There is a mechanism, it's called `DOMContentLoaded`, but that should of course only serve as a last resort and delaying everything until then would probably have a horrible impact on the page's initial rendering performance.

**Comment by WebReflection** [comment]
technically, not even DCL is safe in some case, but I am not making this class just an overly engineered DCL, use DCL if that's what you think is the only option, I have no way to do anything else here.

**Comment by WebReflection** [comment]
I'm also offline, as [the README badge shows](https://github.com/WebReflection/html-parsed-element#html-parsed-element), until the 26th of December so I won't iterate much in here 'cause I won't even have internet these days.

**Comment by franktopel** [comment]
Would wrapping all child elements in a single wrapper element solve this issue? And if so, would that require to configure the mutation observer to only watch childlist changes, and no subtree changes?

The assumption/hope behind this would be that the mutationobserver never gets notified when only part of an element has been added (meaning that when the MO gets notified it's safe to assume the element added is fully parsed).

**Comment by franktopel** [comment]
As someone pointed out here https://stackoverflow.com/questions/53710063/when-a-mutationobserver-fires-for-a-childlist-change-with-a-single-element-is-i?noredirect=1#comment94274693_53710063, could the reason for the reported problem be `subtree: true`?

I will give it another shot without that mutation observer option tomorrow, see if that eleminates the problem.

**Comment by franktopel** [comment]
P.S.: What is the reason you're setting up the mutationobserver on the `parentNode` of the custom element, rather than the custom element itself? 

```javascript
observer.observe(self.parentNode, {childList: true, subtree: true});
```

**Comment by WebReflection** [comment]
@franktopel I'm offline

**Comment by WebReflection** [comment]
btw, had a quick look, I set the parent because I'm interested in its nodes, so maybe `subtree: false`, or omitting it completely, might indeed avoid unexpected triggers.

However, a node at the end of its parent might never see a mutation. If that's OK for you, then try `subtree:false` and let me know how it goes or file a PR, thanks.

**Comment by franktopel** [comment]
Looks like we were able to fix it changing the following:

1. Wrap all component children in a single wrapper `<div class="children-wrapper">` to reduce the number of direct child elements to one:

```javascript
<tabs-component active-tab="1">
   <div class="children-wrapper">
      <ul class="tab-links">
        <li><button type="button">A</button></li>
        <li><button type="button">B</button></li>
        <li><button type="button">C</button></li>
        <li><button type="button">D</button></li>
        <!-- potentially many more lis items and buttons, up to 30 -->
      </ul>
      <div id="A"><!-- ALOT of HTML, like hundreds of lines --></div>
      <div id="B"><!-- ALOT of HTML, like hundreds of lines --></div>
      <div id="C"><!-- ALOT of HTML, like hundreds of lines --></div>
      <div id="D"><!-- ALOT of HTML, like hundreds of lines --></div>
      <!-- potentially many more divs, up to 30 -->
   </div>
</tabs-component>
```

2. Configure the MO so it won't fire off subtree changes:

```javascript
{ childList: true, subtree: false }
```

So far it seems that MO only fires when this single child element is fully parsed - which is exactly what we strived for since we now only have this one child element.

This solution obviously cannot be applied for some customized built-ins, though. Imagine

```html
<ul is="my-list">
  <li></li>
  <li></li>
  <li></li>
</ul>
```

In this example you cannot apply a wrapping element for all children.
